schemaVersion: 2.1.0
metadata:
  name: dev-pwsh
attributes:
  controller.devfile.io/storage-type: ephemeral
  # controller.devfile.io/scc: container-build
components:
  - name: frontend
    container:
      # image: quay.io/mloriedo/universal-developer-image:buildah #registry.ford.com/abaker9/universal-developer-image:ubi9-latest
      image: registry.ford.com/devspaces/universal-developer-image:ubi8-20220705-2025
      # image: registry.ford.com/abaker9/universal-developer-image:pwsh3
      memoryLimit: 2G
      memoryRequest: 1Gi
      cpuLimit: 500m
      cpuRequest: 30m
      # endpoints:
      #   - name: frontend
      #     targetPort: 8079
