apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: ttyd
spec:
  commands:
    - id: init-container-command
      apply:
        component: ttyd-injector
  events:
    preStart:
      - init-container-command
  components:
    - name: ttyd
      volume: {ephemeral: true}
    - name: ttyd-injector
      container:
        image: registry.ford.com/abaker9/ttyd:latest #tsl0922/ttyd:latest
        command: ['cp', '-r', '-n', '/usr/bin/ttyd', '/ttyd/']
        volumeMounts:
          - name: ttyd
            path: /ttyd
        memoryLimit: 128Mi
        memoryRequest: 32Mi
        cpuLimit: 500m
        cpuRequest: 30m