kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: dotnet
spec:
  started: true
  routingClass: che
  template:
    attributes:
      controller.devfile.io/storage-type: ephemeral
    projects:
      - name: dotnet-web-simple
        git:
          remotes:
            origin: "https://github.ford.com/ABAKER9/dotnet-web-simple"
    components:
      - name: editor
        plugin:
          kubernetes:
            name: vs-code
      - name: frontend
        container:
          # image: quay.io/mloriedo/universal-developer-image:ubi8-dw-demo
          image: registry.ford.com/abaker9/universal-developer-image:pwsh
          memoryLimit: 2G
          memoryRequest: 512Mi
          cpuLimit: 2000m
          cpuRequest: 1000m
          args: ["/checode/entrypoint-volume.sh"]
          env: [{name: CODE_HOST, value: "0.0.0.0"}]
          volumeMounts:
            - name: checode
              path: /checode
          endpoints:
            - name: frontend
              targetPort: 8079
            - name: nodejs
              targetPort: 3000
            - name: che-code
              attributes:
                type: main
                discoverable: false
                urlRewriteSupported: true
                contributed-by: che-code.eclipse.org
              targetPort: 3100
              exposure: public
              path: '?tkn=eclipse-che'
              secure: false
              protocol: https
            - name: code-redirect-1
              attributes:
                discoverable: false
                urlRewriteSupported: false
                contributed-by: che-code.eclipse.org
              targetPort: 13131
              exposure: public
              protocol: http
        attributes:
          che-code.eclipse.org/contribute-entry-point: true
          che-code.eclipse.org/contribute-volume-mount/checode: /checode
          che-code.eclipse.org/contribute-endpoint/che-code: 3100
          che-code.eclipse.org/contribute-endpoint/code-redirect-1: 13131
          che-code.eclipse.org/contribute-endpoint/code-redirect-2: 13132
          che-code.eclipse.org/contribute-endpoint/code-redirect-3: 13133
          che-code.eclipse.org/contribute-memoryLimit: true
          che-code.eclipse.org/original-memoryLimit: 1G
          che-code.eclipse.org/contribute-memoryRequest: true
          che-code.eclipse.org/contribute-cpuLimit: true
          che-code.eclipse.org/contribute-cpuRequest: true
          che-code.eclipse.org/contributed-container: frontend
    commands:
      - exec:
          commandLine: dotnet restore
          component: tools
          group:
            kind: build
          workingDir: '${PROJECTS_ROOT}/dotnet-web-simple'
        id: 1-update-dependencies
      - exec:
          commandLine: dotnet build
          component: tools
          group:
            kind: build
          workingDir: '${PROJECTS_ROOT}/dotnet-web-simple'
        id: 2-build
      - exec:
          commandLine: dotnet run
          component: tools
          group:
            kind: run
          workingDir: '${PROJECTS_ROOT}/dotnet-web-simple'
        id: 3-run